name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Get version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Build binaries
      run: |
        # Create dist directory
        mkdir -p dist
        
        # Build for different platforms
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w -X main.version=${{ steps.version.outputs.VERSION }}" -o dist/transcriber-linux-amd64 .
        GOOS=linux GOARCH=arm64 go build -ldflags="-s -w -X main.version=${{ steps.version.outputs.VERSION }}" -o dist/transcriber-linux-arm64 .
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w -X main.version=${{ steps.version.outputs.VERSION }}" -o dist/transcriber-darwin-amd64 .
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w -X main.version=${{ steps.version.outputs.VERSION }}" -o dist/transcriber-darwin-arm64 .
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w -X main.version=${{ steps.version.outputs.VERSION }}" -o dist/transcriber-windows-amd64.exe .
        
        # Create archives
        cd dist
        tar -czf transcriber-linux-amd64.tar.gz transcriber-linux-amd64
        tar -czf transcriber-linux-arm64.tar.gz transcriber-linux-arm64
        tar -czf transcriber-darwin-amd64.tar.gz transcriber-darwin-amd64
        tar -czf transcriber-darwin-arm64.tar.gz transcriber-darwin-arm64
        zip transcriber-windows-amd64.zip transcriber-windows-amd64.exe

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.tar.gz
          dist/*.zip
        body: |
          ## Changes
          
          ## Installation
          
          Download the appropriate binary for your platform and add it to your PATH.
          
          ### Linux/macOS
            ```bash
            curl -L https://github.com/nnanto/transcriber/releases/download/${{ steps.version.outputs.VERSION }}/transcriber-linux-amd64.tar.gz | tar -xz
            sudo mv transcriber-* /usr/local/bin/transcriber

            # Or for macOS
            curl -L https://github.com/nnanto/transcriber/releases/download/${{ steps.version.outputs.VERSION }}/transcriber-darwin-amd64.tar.gz | tar -xz
            sudo mv transcriber-* /usr/local/bin/transcriber
            ```
          
          ### Windows
          Extract the zip file and add the executable to your PATH.
        draft: false
        prerelease: false
